spring.application.name=logitrack
spring.datasource.url=jdbc:postgresql://localhost:5432/logitrack
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true